### ISSUE TITLE
30 seconds timer after unlock

### ISSUE THREAD

**Issue by TW-KM** [2fast-team/2fast#3]
I have the 2fast clients on multiple windows clients in version 1.0.2.0.

After unlock with the password the timer starts always from 30 seconds. So there is a missmatch on the different clients and the login will fail sometimes because the pin code is wrong. Also I don't know which time is correct.

All clients and the server have the same ntp source.

**Comment by jp-weber** [comment]
Hello @TW-KM, the time from the NTP server is currently only taken if the local time is different and a notification is set for the user that the windows time is wrong.

Have you at some point received such a notification? Have you checked the local device time? 

That the timer starts at 30 seconds each time is correct and intentional. The time window for input should actually be large enough in any case, so that the codes are valid. But I can check again if there are cases where the time window is so unfavorable that the time for the input is too short.

**Comment by TW-KM** [comment]
Hello @jp-weber in the settings of the app the ntp is set to system time. I dot not see any notification.

The NTP server is a domain controller and is correct.

The code is just working in the first 10 seconds. After that the code is incorrect.

**Comment by mhellmeier** [comment]
Just a quick sidenote:
The client software calculates the one-time password (OTP) based on the information (key) and the current time. The server where the authorization takes place does the same thing. Everybody knows that it isn't possible to get and enter the correct OTP just in time. Therefore, the authentication server uses intervals to accept "older" and / or "newer" OTPs (see [RFC6238 specification](https://datatracker.ietf.org/doc/html/rfc6238) for more information). This leads to the fact that each server could use different intervals. The OTP may work on `server1` but not on `server2` because it uses a stricter self-made interval.

In relation to your out-of-sync problem: Imagine `client1` running 2fast is a little bit faster than `client2`. After 30 seconds, `client1` shows a new OTP, while `client2` shows the old one. A standard authentication server should accept both OTP.

Are you using the client only against one server and do you host the application of this server. If so, please check if the TOTP validation is implemented correctly.

**Comment by TW-KM** [comment]
Thanks for your help.
